name: Run the Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Run the bot
      run: node index.js
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
